### ISSUE TITLE
yarn.lock

### ISSUE THREAD

**Issue by PierrickV** [val92130/openaio-api#1]
yarn.lock ?? --> .gitignore

**Comment by val92130** [comment]
No, yarn.lock needs to stay in the repo!

> When you run either yarn or yarn add <package>, Yarn will generate a yarn.lock file within the root directory of your package. You don’t need to read or understand this file - just check it into source control. When other people start using Yarn instead of npm, the yarn.lock file will ensure that they get precisely the same dependencies as you have.
